package theauth

import (
	"context"
	"time"
)

// Provider is the contract every OAuth 2.0 / OIDC provider implements. Each
// concrete provider lives in its own sub-package under provider/<name>/ so
// consumers can pick what to import (avoids dragging in HTTP clients for
// providers they will never use).
//
// All methods are called from the OAuth start/callback service flow:
//   - AuthURL  builds the redirect target for /auth/providers/{name}/start.
//   - ExchangeCode swaps the authorization code (plus the PKCE verifier
//     stored at /start time) for a *ProviderToken.
//   - UserInfo turns that token into a normalized *ProviderUser used by
//     the find-or-create logic.
//
// Implementations should be safe to share across goroutines; the service
// only holds one instance per provider name for the process lifetime.
type Provider interface {
	// Name returns the stable registry key, e.g. "github". Routes mount as
	// /auth/providers/{name}/start and /auth/providers/{name}/callback, and
	// it lands in oauth_accounts.provider so it must be URL-safe and lower
	// case.
	Name() string

	// AuthURL builds the absolute authorization URL the user agent will be
	// redirected to. state and codeChallenge are generated by the caller;
	// the implementation only assembles the query string.
	AuthURL(state, codeChallenge, redirectURI string, scopes []string) string

	// ExchangeCode trades an authorization code (and PKCE verifier) for a
	// ProviderToken. Implementations should set a request timeout via ctx;
	// the caller will not.
	ExchangeCode(ctx context.Context, code, codeVerifier, redirectURI string) (*ProviderToken, error)

	// UserInfo returns the canonical user profile for the supplied token.
	// Implementations are responsible for picking the best email (verified +
	// primary if the provider distinguishes them) and reflecting that in
	// ProviderUser.EmailVerified.
	UserInfo(ctx context.Context, token *ProviderToken) (*ProviderUser, error)
}

// ProviderToken is the normalized shape of an OAuth token exchange response.
// Providers vary in which fields they populate (e.g. GitHub typically omits
// RefreshToken and ExpiresAt for "no-expiry" tokens). Storage encrypts the
// access/refresh tokens at rest via crypto.Encrypt.
type ProviderToken struct {
	AccessToken  string
	RefreshToken string
	ExpiresAt    time.Time
	Scope        string
	TokenType    string
}

// ProviderUser is the normalized shape of a provider's userinfo response.
// ID is the provider-stable user identifier (e.g. GitHub numeric id as a
// string) and is what oauth_accounts.provider_user_id stores. Email may be
// empty when the user denied the email scope or has no public email on the
// provider; EmailVerified is true only when the provider attests to it.
type ProviderUser struct {
	ID            string
	Email         string
	EmailVerified bool
	Name          string
	AvatarURL     string
}
