// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
//
// Hand-maintained mirror of the v1.0 model additions (permissions, roles,
// role_permissions, user_roles, audit_events).
//
// The sqlc binary was not available locally at v1.0 codegen time; this file
// matches the v1.30.0 emit format used by models.go and models_v07.go so
// that re-running sqlc generate later produces a stable diff.

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Permission struct {
	ID          pgtype.UUID
	Name        string
	Description string
	CreatedAt   pgtype.Timestamptz
}

type Role struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Name           string
	Description    string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type RolePermission struct {
	RoleID       pgtype.UUID
	PermissionID pgtype.UUID
}

type UserRole struct {
	UserID    pgtype.UUID
	RoleID    pgtype.UUID
	GrantedAt pgtype.Timestamptz
	GrantedBy pgtype.UUID
}

type AuditEvent struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	ActorUserID    pgtype.UUID
	ActorSessionID pgtype.UUID
	Action         string
	TargetType     pgtype.Text
	TargetID       pgtype.Text
	Metadata       []byte
	Ip             pgtype.Text
	UserAgent      pgtype.Text
	CreatedAt      pgtype.Timestamptz
}
