// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type MagicLink struct {
	ID        pgtype.UUID
	Email     string
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type PasswordResetToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Session struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash []byte
	UserAgent string
	Ip        *netip.Addr
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	AuthLevel string
	// v0.7. Pgx Scan target; the column is nullable (ON DELETE SET NULL on
	// organizations). Existing queries that do not SELECT this column leave
	// the field as zero-value pgtype.UUID{Valid:false}.
	ActiveOrganizationID pgtype.UUID
}

type User struct {
	ID              pgtype.UUID
	Email           string
	EmailVerifiedAt pgtype.Timestamptz
	Name            string
	AvatarUrl       string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	PasswordHash    *string
	// v0.7 SCIM columns. Added with NOT NULL DEFAULT '' in migration 0008,
	// so existing reads keep returning empty strings for non-SCIM users.
	ExternalID  string
	GivenName   string
	FamilyName  string
	DisplayName string
}

type OauthAccount struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	Provider        string
	ProviderUserID  string
	AccessTokenEnc  []byte
	RefreshTokenEnc []byte
	ExpiresAt       pgtype.Timestamptz
	Scope           string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type WebauthnCredential struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	CredentialID []byte
	PublicKey    []byte
	SignCount    int64
	Transports   []string
	Aaguid       []byte
	Name         string
	CreatedAt    pgtype.Timestamptz
	LastUsedAt   pgtype.Timestamptz
}

type TotpSecret struct {
	UserID      pgtype.UUID
	SecretEnc   []byte
	ConfirmedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type TotpRecoveryCode struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	CodeHash  []byte
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}
