// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
//
// Hand-maintained mirror of the v0.7 model additions (organizations,
// organization_members, saml_connections, saml_identities, scim_tokens,
// groups, group_members, plus the new users columns external_id,
// given_name, family_name, display_name).
//
// The sqlc binary was not available locally at v0.7 codegen time; this
// file matches the v1.30.0 emit format used by models.go so that
// re-running sqlc generate later produces a stable diff. The User struct
// is amended in models.go itself to add the new columns (sqlc would
// regenerate that file in place).

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Organization struct {
	ID        pgtype.UUID
	Name      string
	Slug      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type OrganizationMember struct {
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
	Role           string
	JoinedAt       pgtype.Timestamptz
}

type SamlConnection struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	IdpEntityID    string
	IdpSsoUrl      string
	IdpX509Cert    string
	SpEntityID     string
	SpAcsUrl       string
	AttributeMap   []byte
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type SamlIdentity struct {
	ID           pgtype.UUID
	ConnectionID pgtype.UUID
	UserID       pgtype.UUID
	NameID       string
	NameIDFormat string
	LastLoginAt  pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

type ScimToken struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	TokenHash      []byte
	Name           string
	CreatedAt      pgtype.Timestamptz
	LastUsedAt     pgtype.Timestamptz
	RevokedAt      pgtype.Timestamptz
}

type Group struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	DisplayName    string
	ExternalID     *string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type GroupMember struct {
	GroupID pgtype.UUID
	UserID  pgtype.UUID
}
