// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql
//
// Hand-maintained mirror of the v0.5 query block (CreateSessionWithAuthLevel
// and downwards through ConsumeRecoveryCodeByID). The sqlc binary was not
// available locally at v0.5 codegen time; this file matches the v1.30.0
// emit format used by queries.sql.go so that re-running sqlc generate later
// produces a stable diff.

package sqlc

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSessionWithAuthLevel = `-- name: CreateSessionWithAuthLevel :one
INSERT INTO sessions (id, user_id, token_hash, user_agent, ip, created_at, expires_at, auth_level)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, token_hash, user_agent, ip, created_at, expires_at, revoked_at, auth_level, active_organization_id
`

type CreateSessionWithAuthLevelParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash []byte
	UserAgent string
	Ip        *netip.Addr
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	AuthLevel string
}

func (q *Queries) CreateSessionWithAuthLevel(ctx context.Context, arg CreateSessionWithAuthLevelParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSessionWithAuthLevel,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.UserAgent,
		arg.Ip,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.AuthLevel,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.Ip,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.AuthLevel,
		&i.ActiveOrganizationID,
	)
	return i, err
}

const updateSessionAuthLevel = `-- name: UpdateSessionAuthLevel :exec
UPDATE sessions SET auth_level = $2 WHERE id = $1
`

type UpdateSessionAuthLevelParams struct {
	ID        pgtype.UUID
	AuthLevel string
}

func (q *Queries) UpdateSessionAuthLevel(ctx context.Context, arg UpdateSessionAuthLevelParams) error {
	_, err := q.db.Exec(ctx, updateSessionAuthLevel, arg.ID, arg.AuthLevel)
	return err
}

const insertWebAuthnCredential = `-- name: InsertWebAuthnCredential :one
INSERT INTO webauthn_credentials (
    id, user_id, credential_id, public_key, sign_count,
    transports, aaguid, name, created_at, last_used_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, credential_id, public_key, sign_count, transports, aaguid, name, created_at, last_used_at
`

type InsertWebAuthnCredentialParams struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	CredentialID []byte
	PublicKey    []byte
	SignCount    int64
	Transports   []string
	Aaguid       []byte
	Name         string
	CreatedAt    pgtype.Timestamptz
	LastUsedAt   pgtype.Timestamptz
}

func (q *Queries) InsertWebAuthnCredential(ctx context.Context, arg InsertWebAuthnCredentialParams) (WebauthnCredential, error) {
	row := q.db.QueryRow(ctx, insertWebAuthnCredential,
		arg.ID,
		arg.UserID,
		arg.CredentialID,
		arg.PublicKey,
		arg.SignCount,
		arg.Transports,
		arg.Aaguid,
		arg.Name,
		arg.CreatedAt,
		arg.LastUsedAt,
	)
	var i WebauthnCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CredentialID,
		&i.PublicKey,
		&i.SignCount,
		&i.Transports,
		&i.Aaguid,
		&i.Name,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const webAuthnCredentialsByUserID = `-- name: WebAuthnCredentialsByUserID :many
SELECT id, user_id, credential_id, public_key, sign_count, transports, aaguid, name, created_at, last_used_at FROM webauthn_credentials WHERE user_id = $1 ORDER BY created_at ASC
`

func (q *Queries) WebAuthnCredentialsByUserID(ctx context.Context, userID pgtype.UUID) ([]WebauthnCredential, error) {
	rows, err := q.db.Query(ctx, webAuthnCredentialsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebauthnCredential{}
	for rows.Next() {
		var i WebauthnCredential
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CredentialID,
			&i.PublicKey,
			&i.SignCount,
			&i.Transports,
			&i.Aaguid,
			&i.Name,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const webAuthnCredentialByCredentialID = `-- name: WebAuthnCredentialByCredentialID :one
SELECT id, user_id, credential_id, public_key, sign_count, transports, aaguid, name, created_at, last_used_at FROM webauthn_credentials WHERE credential_id = $1
`

func (q *Queries) WebAuthnCredentialByCredentialID(ctx context.Context, credentialID []byte) (WebauthnCredential, error) {
	row := q.db.QueryRow(ctx, webAuthnCredentialByCredentialID, credentialID)
	var i WebauthnCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CredentialID,
		&i.PublicKey,
		&i.SignCount,
		&i.Transports,
		&i.Aaguid,
		&i.Name,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const updateWebAuthnSignCount = `-- name: UpdateWebAuthnSignCount :execrows
UPDATE webauthn_credentials
SET sign_count = $2, last_used_at = $3
WHERE credential_id = $1 AND sign_count < $2
`

type UpdateWebAuthnSignCountParams struct {
	CredentialID []byte
	SignCount    int64
	LastUsedAt   pgtype.Timestamptz
}

func (q *Queries) UpdateWebAuthnSignCount(ctx context.Context, arg UpdateWebAuthnSignCountParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateWebAuthnSignCount, arg.CredentialID, arg.SignCount, arg.LastUsedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteWebAuthnCredential = `-- name: DeleteWebAuthnCredential :execrows
DELETE FROM webauthn_credentials WHERE id = $1 AND user_id = $2
`

type DeleteWebAuthnCredentialParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteWebAuthnCredential(ctx context.Context, arg DeleteWebAuthnCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWebAuthnCredential, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertPendingTOTPSecret = `-- name: UpsertPendingTOTPSecret :exec
INSERT INTO totp_secrets (user_id, secret_enc, confirmed_at, created_at, updated_at)
VALUES ($1, $2, NULL, $3, $3)
ON CONFLICT (user_id) DO UPDATE SET
    secret_enc = EXCLUDED.secret_enc,
    confirmed_at = NULL,
    updated_at = EXCLUDED.updated_at
WHERE totp_secrets.confirmed_at IS NULL
`

type UpsertPendingTOTPSecretParams struct {
	UserID    pgtype.UUID
	SecretEnc []byte
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) UpsertPendingTOTPSecret(ctx context.Context, arg UpsertPendingTOTPSecretParams) error {
	_, err := q.db.Exec(ctx, upsertPendingTOTPSecret, arg.UserID, arg.SecretEnc, arg.CreatedAt)
	return err
}

const confirmTOTPSecret = `-- name: ConfirmTOTPSecret :execrows
UPDATE totp_secrets SET confirmed_at = $2, updated_at = $2
WHERE user_id = $1 AND confirmed_at IS NULL
`

type ConfirmTOTPSecretParams struct {
	UserID      pgtype.UUID
	ConfirmedAt pgtype.Timestamptz
}

func (q *Queries) ConfirmTOTPSecret(ctx context.Context, arg ConfirmTOTPSecretParams) (int64, error) {
	result, err := q.db.Exec(ctx, confirmTOTPSecret, arg.UserID, arg.ConfirmedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const totpSecretByUserID = `-- name: TOTPSecretByUserID :one
SELECT user_id, secret_enc, confirmed_at, created_at, updated_at FROM totp_secrets WHERE user_id = $1
`

func (q *Queries) TOTPSecretByUserID(ctx context.Context, userID pgtype.UUID) (TotpSecret, error) {
	row := q.db.QueryRow(ctx, totpSecretByUserID, userID)
	var i TotpSecret
	err := row.Scan(
		&i.UserID,
		&i.SecretEnc,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTOTPSecret = `-- name: DeleteTOTPSecret :exec
DELETE FROM totp_secrets WHERE user_id = $1
`

func (q *Queries) DeleteTOTPSecret(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTOTPSecret, userID)
	return err
}

const deleteRecoveryCodesByUserID = `-- name: DeleteRecoveryCodesByUserID :exec
DELETE FROM totp_recovery_codes WHERE user_id = $1
`

func (q *Queries) DeleteRecoveryCodesByUserID(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRecoveryCodesByUserID, userID)
	return err
}

const insertRecoveryCode = `-- name: InsertRecoveryCode :exec
INSERT INTO totp_recovery_codes (id, user_id, code_hash, created_at)
VALUES ($1, $2, $3, $4)
`

type InsertRecoveryCodeParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	CodeHash  []byte
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertRecoveryCode(ctx context.Context, arg InsertRecoveryCodeParams) error {
	_, err := q.db.Exec(ctx, insertRecoveryCode, arg.ID, arg.UserID, arg.CodeHash, arg.CreatedAt)
	return err
}

const recoveryCodesByUserID = `-- name: RecoveryCodesByUserID :many
SELECT id, user_id, code_hash, used_at, created_at FROM totp_recovery_codes WHERE user_id = $1 AND used_at IS NULL
`

func (q *Queries) RecoveryCodesByUserID(ctx context.Context, userID pgtype.UUID) ([]TotpRecoveryCode, error) {
	rows, err := q.db.Query(ctx, recoveryCodesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TotpRecoveryCode{}
	for rows.Next() {
		var i TotpRecoveryCode
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CodeHash,
			&i.UsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const consumeRecoveryCodeByID = `-- name: ConsumeRecoveryCodeByID :execrows
UPDATE totp_recovery_codes SET used_at = $2
WHERE id = $1 AND used_at IS NULL
`

type ConsumeRecoveryCodeByIDParams struct {
	ID     pgtype.UUID
	UsedAt pgtype.Timestamptz
}

func (q *Queries) ConsumeRecoveryCodeByID(ctx context.Context, arg ConsumeRecoveryCodeByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeRecoveryCodeByID, arg.ID, arg.UsedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
