// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeMagicLink = `-- name: ConsumeMagicLink :one
UPDATE magic_links SET used_at = now()
WHERE token_hash = $1 AND used_at IS NULL AND expires_at > now()
RETURNING id, email, token_hash, expires_at, used_at, created_at
`

func (q *Queries) ConsumeMagicLink(ctx context.Context, tokenHash []byte) (MagicLink, error) {
	row := q.db.QueryRow(ctx, consumeMagicLink, tokenHash)
	var i MagicLink
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createMagicLink = `-- name: CreateMagicLink :exec
INSERT INTO magic_links (id, email, token_hash, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateMagicLinkParams struct {
	ID        pgtype.UUID
	Email     string
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateMagicLink(ctx context.Context, arg CreateMagicLinkParams) error {
	_, err := q.db.Exec(ctx, createMagicLink,
		arg.ID,
		arg.Email,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, token_hash, user_agent, ip, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, token_hash, user_agent, ip, created_at, expires_at, revoked_at
`

type CreateSessionParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash []byte
	UserAgent string
	Ip        *netip.Addr
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.UserAgent,
		arg.Ip,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.Ip,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, name, avatar_url, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email, email_verified_at, name, avatar_url, created_at, updated_at
`

type CreateUserParams struct {
	ID        pgtype.UUID
	Email     string
	Name      string
	AvatarUrl string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.AvatarUrl,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE users SET email_verified_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) MarkEmailVerified(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markEmailVerified, id)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = now() WHERE id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const revokeUserSessions = `-- name: RevokeUserSessions :exec
UPDATE sessions SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeUserSessions(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeUserSessions, userID)
	return err
}

const sessionByTokenHash = `-- name: SessionByTokenHash :one
SELECT id, user_id, token_hash, user_agent, ip, created_at, expires_at, revoked_at FROM sessions WHERE token_hash = $1
`

func (q *Queries) SessionByTokenHash(ctx context.Context, tokenHash []byte) (Session, error) {
	row := q.db.QueryRow(ctx, sessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.Ip,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const userByEmail = `-- name: UserByEmail :one
SELECT id, email, email_verified_at, name, avatar_url, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) UserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, userByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userByID = `-- name: UserByID :one
SELECT id, email, email_verified_at, name, avatar_url, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) UserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, userByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
