// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql
//
// Hand-maintained mirror of the v0.7 query block (organizations,
// organization_members, sessions.active_organization_id, saml_connections,
// saml_identities, scim_tokens, groups, group_members, plus the SCIM-scoped
// users views). The sqlc binary was not available locally at v0.7 codegen
// time; this file matches the v1.30.0 emit format used by queries.sql.go
// and queries_v05.sql.go so re-running sqlc generate later produces a
// stable diff.

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

// ---------- organizations ----------

const insertOrganization = `-- name: InsertOrganization :one
INSERT INTO organizations (id, name, slug, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, slug, created_at, updated_at
`

type InsertOrganizationParams struct {
	ID        pgtype.UUID
	Name      string
	Slug      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) InsertOrganization(ctx context.Context, arg InsertOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, insertOrganization,
		arg.ID, arg.Name, arg.Slug, arg.CreatedAt, arg.UpdatedAt,
	)
	var i Organization
	err := row.Scan(&i.ID, &i.Name, &i.Slug, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const organizationByID = `-- name: OrganizationByID :one
SELECT id, name, slug, created_at, updated_at FROM organizations WHERE id = $1
`

func (q *Queries) OrganizationByID(ctx context.Context, id pgtype.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, organizationByID, id)
	var i Organization
	err := row.Scan(&i.ID, &i.Name, &i.Slug, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const organizationBySlug = `-- name: OrganizationBySlug :one
SELECT id, name, slug, created_at, updated_at FROM organizations WHERE slug = $1
`

func (q *Queries) OrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRow(ctx, organizationBySlug, slug)
	var i Organization
	err := row.Scan(&i.ID, &i.Name, &i.Slug, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const updateOrganization = `-- name: UpdateOrganization :execrows
UPDATE organizations SET name = $2, slug = $3, updated_at = now() WHERE id = $1
`

type UpdateOrganizationParams struct {
	ID   pgtype.UUID
	Name string
	Slug string
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (int64, error) {
	r, err := q.db.Exec(ctx, updateOrganization, arg.ID, arg.Name, arg.Slug)
	if err != nil {
		return 0, err
	}
	return r.RowsAffected(), nil
}

const deleteOrganization = `-- name: DeleteOrganization :execrows
DELETE FROM organizations WHERE id = $1
`

func (q *Queries) DeleteOrganization(ctx context.Context, id pgtype.UUID) (int64, error) {
	r, err := q.db.Exec(ctx, deleteOrganization, id)
	if err != nil {
		return 0, err
	}
	return r.RowsAffected(), nil
}

const upsertOrganizationMember = `-- name: UpsertOrganizationMember :exec
INSERT INTO organization_members (organization_id, user_id, role, joined_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (organization_id, user_id) DO UPDATE SET role = EXCLUDED.role
`

type UpsertOrganizationMemberParams struct {
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
	Role           string
	JoinedAt       pgtype.Timestamptz
}

func (q *Queries) UpsertOrganizationMember(ctx context.Context, arg UpsertOrganizationMemberParams) error {
	_, err := q.db.Exec(ctx, upsertOrganizationMember, arg.OrganizationID, arg.UserID, arg.Role, arg.JoinedAt)
	return err
}

const deleteOrganizationMember = `-- name: DeleteOrganizationMember :execrows
DELETE FROM organization_members WHERE organization_id = $1 AND user_id = $2
`

type DeleteOrganizationMemberParams struct {
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
}

func (q *Queries) DeleteOrganizationMember(ctx context.Context, arg DeleteOrganizationMemberParams) (int64, error) {
	r, err := q.db.Exec(ctx, deleteOrganizationMember, arg.OrganizationID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return r.RowsAffected(), nil
}

const organizationMembersByOrg = `-- name: OrganizationMembersByOrg :many
SELECT organization_id, user_id, role, joined_at FROM organization_members WHERE organization_id = $1 ORDER BY joined_at ASC
`

func (q *Queries) OrganizationMembersByOrg(ctx context.Context, organizationID pgtype.UUID) ([]OrganizationMember, error) {
	rows, err := q.db.Query(ctx, organizationMembersByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganizationMember{}
	for rows.Next() {
		var i OrganizationMember
		if err := rows.Scan(&i.OrganizationID, &i.UserID, &i.Role, &i.JoinedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const organizationsByUser = `-- name: OrganizationsByUser :many
SELECT o.id, o.name, o.slug, o.created_at, o.updated_at FROM organizations o
  JOIN organization_members m ON m.organization_id = o.id
 WHERE m.user_id = $1
 ORDER BY o.created_at ASC
`

func (q *Queries) OrganizationsByUser(ctx context.Context, userID pgtype.UUID) ([]Organization, error) {
	rows, err := q.db.Query(ctx, organizationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(&i.ID, &i.Name, &i.Slug, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const organizationMemberRole = `-- name: OrganizationMemberRole :one
SELECT role FROM organization_members WHERE organization_id = $1 AND user_id = $2
`

type OrganizationMemberRoleParams struct {
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
}

func (q *Queries) OrganizationMemberRole(ctx context.Context, arg OrganizationMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, organizationMemberRole, arg.OrganizationID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const setSessionActiveOrganization = `-- name: SetSessionActiveOrganization :execrows
UPDATE sessions SET active_organization_id = $2 WHERE id = $1
`

type SetSessionActiveOrganizationParams struct {
	ID                   pgtype.UUID
	ActiveOrganizationID pgtype.UUID
}

func (q *Queries) SetSessionActiveOrganization(ctx context.Context, arg SetSessionActiveOrganizationParams) (int64, error) {
	r, err := q.db.Exec(ctx, setSessionActiveOrganization, arg.ID, arg.ActiveOrganizationID)
	if err != nil {
		return 0, err
	}
	return r.RowsAffected(), nil
}

// ---------- saml ----------

const insertSAMLConnection = `-- name: InsertSAMLConnection :one
INSERT INTO saml_connections (
    id, organization_id, idp_entity_id, idp_sso_url, idp_x509_cert,
    sp_entity_id, sp_acs_url, attribute_map, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, organization_id, idp_entity_id, idp_sso_url, idp_x509_cert, sp_entity_id, sp_acs_url, attribute_map, created_at, updated_at
`

type InsertSAMLConnectionParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	IdpEntityID    string
	IdpSsoUrl      string
	IdpX509Cert    string
	SpEntityID     string
	SpAcsUrl       string
	AttributeMap   []byte
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) InsertSAMLConnection(ctx context.Context, arg InsertSAMLConnectionParams) (SamlConnection, error) {
	row := q.db.QueryRow(ctx, insertSAMLConnection,
		arg.ID, arg.OrganizationID, arg.IdpEntityID, arg.IdpSsoUrl, arg.IdpX509Cert,
		arg.SpEntityID, arg.SpAcsUrl, arg.AttributeMap, arg.CreatedAt, arg.UpdatedAt,
	)
	var i SamlConnection
	err := row.Scan(
		&i.ID, &i.OrganizationID, &i.IdpEntityID, &i.IdpSsoUrl, &i.IdpX509Cert,
		&i.SpEntityID, &i.SpAcsUrl, &i.AttributeMap, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const updateSAMLConnection = `-- name: UpdateSAMLConnection :execrows
UPDATE saml_connections SET
    idp_entity_id = $2, idp_sso_url = $3, idp_x509_cert = $4,
    sp_entity_id = $5, sp_acs_url = $6, attribute_map = $7,
    updated_at = now()
WHERE id = $1
`

type UpdateSAMLConnectionParams struct {
	ID           pgtype.UUID
	IdpEntityID  string
	IdpSsoUrl    string
	IdpX509Cert  string
	SpEntityID   string
	SpAcsUrl     string
	AttributeMap []byte
}

func (q *Queries) UpdateSAMLConnection(ctx context.Context, arg UpdateSAMLConnectionParams) (int64, error) {
	r, err := q.db.Exec(ctx, updateSAMLConnection,
		arg.ID, arg.IdpEntityID, arg.IdpSsoUrl, arg.IdpX509Cert,
		arg.SpEntityID, arg.SpAcsUrl, arg.AttributeMap,
	)
	if err != nil {
		return 0, err
	}
	return r.RowsAffected(), nil
}

const deleteSAMLConnection = `-- name: DeleteSAMLConnection :execrows
DELETE FROM saml_connections WHERE id = $1
`

func (q *Queries) DeleteSAMLConnection(ctx context.Context, id pgtype.UUID) (int64, error) {
	r, err := q.db.Exec(ctx, deleteSAMLConnection, id)
	if err != nil {
		return 0, err
	}
	return r.RowsAffected(), nil
}

const samlConnectionByID = `-- name: SAMLConnectionByID :one
SELECT id, organization_id, idp_entity_id, idp_sso_url, idp_x509_cert, sp_entity_id, sp_acs_url, attribute_map, created_at, updated_at FROM saml_connections WHERE id = $1
`

func (q *Queries) SAMLConnectionByID(ctx context.Context, id pgtype.UUID) (SamlConnection, error) {
	row := q.db.QueryRow(ctx, samlConnectionByID, id)
	var i SamlConnection
	err := row.Scan(
		&i.ID, &i.OrganizationID, &i.IdpEntityID, &i.IdpSsoUrl, &i.IdpX509Cert,
		&i.SpEntityID, &i.SpAcsUrl, &i.AttributeMap, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const samlConnectionsByOrg = `-- name: SAMLConnectionsByOrg :many
SELECT id, organization_id, idp_entity_id, idp_sso_url, idp_x509_cert, sp_entity_id, sp_acs_url, attribute_map, created_at, updated_at FROM saml_connections WHERE organization_id = $1 ORDER BY created_at ASC
`

func (q *Queries) SAMLConnectionsByOrg(ctx context.Context, organizationID pgtype.UUID) ([]SamlConnection, error) {
	rows, err := q.db.Query(ctx, samlConnectionsByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SamlConnection{}
	for rows.Next() {
		var i SamlConnection
		if err := rows.Scan(
			&i.ID, &i.OrganizationID, &i.IdpEntityID, &i.IdpSsoUrl, &i.IdpX509Cert,
			&i.SpEntityID, &i.SpAcsUrl, &i.AttributeMap, &i.CreatedAt, &i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const upsertSAMLIdentity = `-- name: UpsertSAMLIdentity :one
INSERT INTO saml_identities (id, connection_id, user_id, name_id, name_id_format, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (connection_id, name_id) DO UPDATE SET
    user_id = EXCLUDED.user_id,
    name_id_format = EXCLUDED.name_id_format
RETURNING id, connection_id, user_id, name_id, name_id_format, last_login_at, created_at
`

type UpsertSAMLIdentityParams struct {
	ID           pgtype.UUID
	ConnectionID pgtype.UUID
	UserID       pgtype.UUID
	NameID       string
	NameIDFormat string
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) UpsertSAMLIdentity(ctx context.Context, arg UpsertSAMLIdentityParams) (SamlIdentity, error) {
	row := q.db.QueryRow(ctx, upsertSAMLIdentity,
		arg.ID, arg.ConnectionID, arg.UserID, arg.NameID, arg.NameIDFormat, arg.CreatedAt,
	)
	var i SamlIdentity
	err := row.Scan(
		&i.ID, &i.ConnectionID, &i.UserID, &i.NameID, &i.NameIDFormat, &i.LastLoginAt, &i.CreatedAt,
	)
	return i, err
}

const samlIdentityByConnectionAndNameID = `-- name: SAMLIdentityByConnectionAndNameID :one
SELECT id, connection_id, user_id, name_id, name_id_format, last_login_at, created_at FROM saml_identities WHERE connection_id = $1 AND name_id = $2
`

type SAMLIdentityByConnectionAndNameIDParams struct {
	ConnectionID pgtype.UUID
	NameID       string
}

func (q *Queries) SAMLIdentityByConnectionAndNameID(ctx context.Context, arg SAMLIdentityByConnectionAndNameIDParams) (SamlIdentity, error) {
	row := q.db.QueryRow(ctx, samlIdentityByConnectionAndNameID, arg.ConnectionID, arg.NameID)
	var i SamlIdentity
	err := row.Scan(
		&i.ID, &i.ConnectionID, &i.UserID, &i.NameID, &i.NameIDFormat, &i.LastLoginAt, &i.CreatedAt,
	)
	return i, err
}

const touchSAMLIdentityLastLogin = `-- name: TouchSAMLIdentityLastLogin :exec
UPDATE saml_identities SET last_login_at = $2 WHERE id = $1
`

type TouchSAMLIdentityLastLoginParams struct {
	ID          pgtype.UUID
	LastLoginAt pgtype.Timestamptz
}

func (q *Queries) TouchSAMLIdentityLastLogin(ctx context.Context, arg TouchSAMLIdentityLastLoginParams) error {
	_, err := q.db.Exec(ctx, touchSAMLIdentityLastLogin, arg.ID, arg.LastLoginAt)
	return err
}

// ---------- scim tokens ----------

const insertSCIMToken = `-- name: InsertSCIMToken :one
INSERT INTO scim_tokens (id, organization_id, token_hash, name, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, organization_id, token_hash, name, created_at, last_used_at, revoked_at
`

type InsertSCIMTokenParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	TokenHash      []byte
	Name           string
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) InsertSCIMToken(ctx context.Context, arg InsertSCIMTokenParams) (ScimToken, error) {
	row := q.db.QueryRow(ctx, insertSCIMToken, arg.ID, arg.OrganizationID, arg.TokenHash, arg.Name, arg.CreatedAt)
	var i ScimToken
	err := row.Scan(&i.ID, &i.OrganizationID, &i.TokenHash, &i.Name, &i.CreatedAt, &i.LastUsedAt, &i.RevokedAt)
	return i, err
}

const scimTokenByHash = `-- name: SCIMTokenByHash :one
SELECT id, organization_id, token_hash, name, created_at, last_used_at, revoked_at FROM scim_tokens WHERE token_hash = $1
`

func (q *Queries) SCIMTokenByHash(ctx context.Context, tokenHash []byte) (ScimToken, error) {
	row := q.db.QueryRow(ctx, scimTokenByHash, tokenHash)
	var i ScimToken
	err := row.Scan(&i.ID, &i.OrganizationID, &i.TokenHash, &i.Name, &i.CreatedAt, &i.LastUsedAt, &i.RevokedAt)
	return i, err
}

const scimTokensByOrg = `-- name: SCIMTokensByOrg :many
SELECT id, organization_id, token_hash, name, created_at, last_used_at, revoked_at FROM scim_tokens WHERE organization_id = $1 ORDER BY created_at ASC
`

func (q *Queries) SCIMTokensByOrg(ctx context.Context, organizationID pgtype.UUID) ([]ScimToken, error) {
	rows, err := q.db.Query(ctx, scimTokensByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScimToken{}
	for rows.Next() {
		var i ScimToken
		if err := rows.Scan(&i.ID, &i.OrganizationID, &i.TokenHash, &i.Name, &i.CreatedAt, &i.LastUsedAt, &i.RevokedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const revokeSCIMTokenByID = `-- name: RevokeSCIMTokenByID :execrows
UPDATE scim_tokens SET revoked_at = $2 WHERE id = $1
`

type RevokeSCIMTokenByIDParams struct {
	ID        pgtype.UUID
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) RevokeSCIMTokenByID(ctx context.Context, arg RevokeSCIMTokenByIDParams) (int64, error) {
	r, err := q.db.Exec(ctx, revokeSCIMTokenByID, arg.ID, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return r.RowsAffected(), nil
}

const touchSCIMTokenLastUsed = `-- name: TouchSCIMTokenLastUsed :exec
UPDATE scim_tokens SET last_used_at = $2 WHERE id = $1
`

type TouchSCIMTokenLastUsedParams struct {
	ID         pgtype.UUID
	LastUsedAt pgtype.Timestamptz
}

func (q *Queries) TouchSCIMTokenLastUsed(ctx context.Context, arg TouchSCIMTokenLastUsedParams) error {
	_, err := q.db.Exec(ctx, touchSCIMTokenLastUsed, arg.ID, arg.LastUsedAt)
	return err
}

// ---------- users scoped queries ----------
//
// SELECT * on users returns the v0.7 columns we added at the tail
// (external_id, given_name, family_name, display_name). Postgres returns
// columns in ALTER TABLE order; we Scan into the same order. Pre-v0.7
// stored procs SELECT users.* will continue to compile because the older
// User scan in queries.sql.go does not reference the new columns and
// pgx silently ignores extra columns on a Scan target that has fewer
// fields than the row.
//
// We deliberately do not regenerate queries.sql.go for CreateUser /
// UserByEmail / UserByID; those keep returning the v0.5 column set and
// add empty strings via the rowToUser mapper.
//
// The two scoped queries (ListUsersByOrganization, UserByExternalIDInOrg)
// SELECT u.* and we Scan into the new struct.

const listUsersByOrganization = `-- name: ListUsersByOrganization :many
SELECT u.id, u.email, u.email_verified_at, u.name, u.avatar_url, u.created_at, u.updated_at, u.password_hash, u.external_id, u.given_name, u.family_name, u.display_name FROM users u
  JOIN organization_members m ON m.user_id = u.id
 WHERE m.organization_id = $1
   AND ($2::text = '' OR u.email = $2)
   AND ($3::text = '' OR u.external_id = $3)
   AND ($4::text = '' OR u.email = $4)
 ORDER BY u.created_at ASC
 OFFSET $5 LIMIT $6
`

type ListUsersByOrganizationParams struct {
	OrganizationID pgtype.UUID
	UserName       string
	ExternalID     string
	Email          string
	OffsetN        int32
	LimitN         int32
}

func (q *Queries) ListUsersByOrganization(ctx context.Context, arg ListUsersByOrganizationParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByOrganization,
		arg.OrganizationID, arg.UserName, arg.ExternalID, arg.Email, arg.OffsetN, arg.LimitN,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID, &i.Email, &i.EmailVerifiedAt, &i.Name, &i.AvatarUrl,
			&i.CreatedAt, &i.UpdatedAt, &i.PasswordHash,
			&i.ExternalID, &i.GivenName, &i.FamilyName, &i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const countUsersByOrganization = `-- name: CountUsersByOrganization :one
SELECT count(*) FROM users u
  JOIN organization_members m ON m.user_id = u.id
 WHERE m.organization_id = $1
   AND ($2::text = '' OR u.email = $2)
   AND ($3::text = '' OR u.external_id = $3)
   AND ($4::text = '' OR u.email = $4)
`

type CountUsersByOrganizationParams struct {
	OrganizationID pgtype.UUID
	UserName       string
	ExternalID     string
	Email          string
}

func (q *Queries) CountUsersByOrganization(ctx context.Context, arg CountUsersByOrganizationParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByOrganization, arg.OrganizationID, arg.UserName, arg.ExternalID, arg.Email)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const userByExternalIDInOrg = `-- name: UserByExternalIDInOrg :one
SELECT u.id, u.email, u.email_verified_at, u.name, u.avatar_url, u.created_at, u.updated_at, u.password_hash, u.external_id, u.given_name, u.family_name, u.display_name FROM users u
  JOIN organization_members m ON m.user_id = u.id
 WHERE m.organization_id = $1 AND u.external_id = $2
`

type UserByExternalIDInOrgParams struct {
	OrganizationID pgtype.UUID
	ExternalID     string
}

func (q *Queries) UserByExternalIDInOrg(ctx context.Context, arg UserByExternalIDInOrgParams) (User, error) {
	row := q.db.QueryRow(ctx, userByExternalIDInOrg, arg.OrganizationID, arg.ExternalID)
	var i User
	err := row.Scan(
		&i.ID, &i.Email, &i.EmailVerifiedAt, &i.Name, &i.AvatarUrl,
		&i.CreatedAt, &i.UpdatedAt, &i.PasswordHash,
		&i.ExternalID, &i.GivenName, &i.FamilyName, &i.DisplayName,
	)
	return i, err
}

const updateUserSCIM = `-- name: UpdateUserSCIM :execrows
UPDATE users SET
    email = $2, name = $3, avatar_url = $4,
    external_id = $5, given_name = $6, family_name = $7, display_name = $8,
    updated_at = now()
WHERE id = $1
`

type UpdateUserSCIMParams struct {
	ID          pgtype.UUID
	Email       string
	Name        string
	AvatarUrl   string
	ExternalID  string
	GivenName   string
	FamilyName  string
	DisplayName string
}

func (q *Queries) UpdateUserSCIM(ctx context.Context, arg UpdateUserSCIMParams) (int64, error) {
	r, err := q.db.Exec(ctx, updateUserSCIM,
		arg.ID, arg.Email, arg.Name, arg.AvatarUrl,
		arg.ExternalID, arg.GivenName, arg.FamilyName, arg.DisplayName,
	)
	if err != nil {
		return 0, err
	}
	return r.RowsAffected(), nil
}

// ---------- groups ----------

const insertGroup = `-- name: InsertGroup :one
INSERT INTO groups (id, organization_id, display_name, external_id, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, organization_id, display_name, external_id, created_at, updated_at
`

type InsertGroupParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	DisplayName    string
	ExternalID     *string
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) InsertGroup(ctx context.Context, arg InsertGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, insertGroup, arg.ID, arg.OrganizationID, arg.DisplayName, arg.ExternalID, arg.CreatedAt)
	var i Group
	err := row.Scan(&i.ID, &i.OrganizationID, &i.DisplayName, &i.ExternalID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const groupByID = `-- name: GroupByID :one
SELECT id, organization_id, display_name, external_id, created_at, updated_at FROM groups WHERE id = $1
`

func (q *Queries) GroupByID(ctx context.Context, id pgtype.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, groupByID, id)
	var i Group
	err := row.Scan(&i.ID, &i.OrganizationID, &i.DisplayName, &i.ExternalID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const groupByExternalIDInOrg = `-- name: GroupByExternalIDInOrg :one
SELECT id, organization_id, display_name, external_id, created_at, updated_at FROM groups WHERE organization_id = $1 AND external_id = $2
`

type GroupByExternalIDInOrgParams struct {
	OrganizationID pgtype.UUID
	ExternalID     *string
}

func (q *Queries) GroupByExternalIDInOrg(ctx context.Context, arg GroupByExternalIDInOrgParams) (Group, error) {
	row := q.db.QueryRow(ctx, groupByExternalIDInOrg, arg.OrganizationID, arg.ExternalID)
	var i Group
	err := row.Scan(&i.ID, &i.OrganizationID, &i.DisplayName, &i.ExternalID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const updateGroup = `-- name: UpdateGroup :execrows
UPDATE groups SET display_name = $2, external_id = $3, updated_at = now() WHERE id = $1
`

type UpdateGroupParams struct {
	ID          pgtype.UUID
	DisplayName string
	ExternalID  *string
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (int64, error) {
	r, err := q.db.Exec(ctx, updateGroup, arg.ID, arg.DisplayName, arg.ExternalID)
	if err != nil {
		return 0, err
	}
	return r.RowsAffected(), nil
}

const deleteGroup = `-- name: DeleteGroup :execrows
DELETE FROM groups WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id pgtype.UUID) (int64, error) {
	r, err := q.db.Exec(ctx, deleteGroup, id)
	if err != nil {
		return 0, err
	}
	return r.RowsAffected(), nil
}

const listGroupsByOrganization = `-- name: ListGroupsByOrganization :many
SELECT id, organization_id, display_name, external_id, created_at, updated_at FROM groups
 WHERE organization_id = $1
   AND ($2::text = '' OR display_name = $2)
   AND ($3::text = '' OR external_id = $3)
 ORDER BY created_at ASC
 OFFSET $4 LIMIT $5
`

type ListGroupsByOrganizationParams struct {
	OrganizationID pgtype.UUID
	DisplayName    string
	ExternalID     string
	OffsetN        int32
	LimitN         int32
}

func (q *Queries) ListGroupsByOrganization(ctx context.Context, arg ListGroupsByOrganizationParams) ([]Group, error) {
	rows, err := q.db.Query(ctx, listGroupsByOrganization,
		arg.OrganizationID, arg.DisplayName, arg.ExternalID, arg.OffsetN, arg.LimitN,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(&i.ID, &i.OrganizationID, &i.DisplayName, &i.ExternalID, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const countGroupsByOrganization = `-- name: CountGroupsByOrganization :one
SELECT count(*) FROM groups
 WHERE organization_id = $1
   AND ($2::text = '' OR display_name = $2)
   AND ($3::text = '' OR external_id = $3)
`

type CountGroupsByOrganizationParams struct {
	OrganizationID pgtype.UUID
	DisplayName    string
	ExternalID     string
}

func (q *Queries) CountGroupsByOrganization(ctx context.Context, arg CountGroupsByOrganizationParams) (int64, error) {
	row := q.db.QueryRow(ctx, countGroupsByOrganization, arg.OrganizationID, arg.DisplayName, arg.ExternalID)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const deleteAllGroupMembers = `-- name: DeleteAllGroupMembers :exec
DELETE FROM group_members WHERE group_id = $1
`

func (q *Queries) DeleteAllGroupMembers(ctx context.Context, groupID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllGroupMembers, groupID)
	return err
}

const insertGroupMember = `-- name: InsertGroupMember :exec
INSERT INTO group_members (group_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertGroupMemberParams struct {
	GroupID pgtype.UUID
	UserID  pgtype.UUID
}

func (q *Queries) InsertGroupMember(ctx context.Context, arg InsertGroupMemberParams) error {
	_, err := q.db.Exec(ctx, insertGroupMember, arg.GroupID, arg.UserID)
	return err
}

const deleteGroupMember = `-- name: DeleteGroupMember :exec
DELETE FROM group_members WHERE group_id = $1 AND user_id = $2
`

type DeleteGroupMemberParams struct {
	GroupID pgtype.UUID
	UserID  pgtype.UUID
}

func (q *Queries) DeleteGroupMember(ctx context.Context, arg DeleteGroupMemberParams) error {
	_, err := q.db.Exec(ctx, deleteGroupMember, arg.GroupID, arg.UserID)
	return err
}

const groupMembersByGroupID = `-- name: GroupMembersByGroupID :many
SELECT user_id FROM group_members WHERE group_id = $1 ORDER BY user_id ASC
`

func (q *Queries) GroupMembersByGroupID(ctx context.Context, groupID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, groupMembersByGroupID, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var u pgtype.UUID
		if err := rows.Scan(&u); err != nil {
			return nil, err
		}
		items = append(items, u)
	}
	return items, rows.Err()
}
