// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql
//
// Hand-maintained mirror of the v1.0 query block (permissions, roles,
// role_permissions, user_roles, audit_events.InsertAuditEvent). The query
// builder for the audit read path lives in postgres_v10.go (filter combos
// vary too much for a fixed sqlc query).
//
// Matches the v1.30.0 emit style used by queries.sql.go, queries_v05.sql.go,
// and queries_v07.sql.go so that re-running sqlc generate later produces a
// stable diff.

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

// ---------- permissions ----------

const insertPermission = `-- name: InsertPermission :one
INSERT INTO permissions (id, name, description, created_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (name) DO UPDATE SET description = permissions.description
RETURNING id, name, description, created_at
`

type InsertPermissionParams struct {
	ID          pgtype.UUID
	Name        string
	Description string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) InsertPermission(ctx context.Context, arg InsertPermissionParams) (Permission, error) {
	row := q.db.QueryRow(ctx, insertPermission, arg.ID, arg.Name, arg.Description, arg.CreatedAt)
	var i Permission
	err := row.Scan(&i.ID, &i.Name, &i.Description, &i.CreatedAt)
	return i, err
}

const permissionByName = `-- name: PermissionByName :one
SELECT id, name, description, created_at FROM permissions WHERE name = $1
`

func (q *Queries) PermissionByName(ctx context.Context, name string) (Permission, error) {
	row := q.db.QueryRow(ctx, permissionByName, name)
	var i Permission
	err := row.Scan(&i.ID, &i.Name, &i.Description, &i.CreatedAt)
	return i, err
}

const listPermissions = `-- name: ListPermissions :many
SELECT id, name, description, created_at FROM permissions ORDER BY name ASC
`

func (q *Queries) ListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.ID, &i.Name, &i.Description, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

// ---------- roles ----------

const insertRole = `-- name: InsertRole :one
INSERT INTO roles (id, organization_id, name, description, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, organization_id, name, description, created_at, updated_at
`

type InsertRoleParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Name           string
	Description    string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) InsertRole(ctx context.Context, arg InsertRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, insertRole,
		arg.ID, arg.OrganizationID, arg.Name, arg.Description, arg.CreatedAt, arg.UpdatedAt,
	)
	var i Role
	err := row.Scan(&i.ID, &i.OrganizationID, &i.Name, &i.Description, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const updateRoleRow = `-- name: UpdateRoleRow :one
UPDATE roles SET name = $2, description = $3, updated_at = now() WHERE id = $1
RETURNING id, organization_id, name, description, created_at, updated_at
`

type UpdateRoleRowParams struct {
	ID          pgtype.UUID
	Name        string
	Description string
}

func (q *Queries) UpdateRoleRow(ctx context.Context, arg UpdateRoleRowParams) (Role, error) {
	row := q.db.QueryRow(ctx, updateRoleRow, arg.ID, arg.Name, arg.Description)
	var i Role
	err := row.Scan(&i.ID, &i.OrganizationID, &i.Name, &i.Description, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const deleteRoleRow = `-- name: DeleteRoleRow :execrows
DELETE FROM roles WHERE id = $1
`

func (q *Queries) DeleteRoleRow(ctx context.Context, id pgtype.UUID) (int64, error) {
	r, err := q.db.Exec(ctx, deleteRoleRow, id)
	if err != nil {
		return 0, err
	}
	return r.RowsAffected(), nil
}

const roleByID = `-- name: RoleByID :one
SELECT id, organization_id, name, description, created_at, updated_at FROM roles WHERE id = $1
`

func (q *Queries) RoleByID(ctx context.Context, id pgtype.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, roleByID, id)
	var i Role
	err := row.Scan(&i.ID, &i.OrganizationID, &i.Name, &i.Description, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const roleByOrgAndName = `-- name: RoleByOrgAndName :one
SELECT id, organization_id, name, description, created_at, updated_at
  FROM roles
 WHERE name = $1
   AND ((organization_id IS NULL AND $2::uuid IS NULL) OR organization_id = $2::uuid)
`

type RoleByOrgAndNameParams struct {
	Name           string
	OrganizationID pgtype.UUID
}

func (q *Queries) RoleByOrgAndName(ctx context.Context, arg RoleByOrgAndNameParams) (Role, error) {
	row := q.db.QueryRow(ctx, roleByOrgAndName, arg.Name, arg.OrganizationID)
	var i Role
	err := row.Scan(&i.ID, &i.OrganizationID, &i.Name, &i.Description, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const rolesByOrganization = `-- name: RolesByOrganization :many
SELECT id, organization_id, name, description, created_at, updated_at
  FROM roles
 WHERE (organization_id IS NULL AND $1::uuid IS NULL) OR organization_id = $1::uuid
 ORDER BY name ASC
`

func (q *Queries) RolesByOrganization(ctx context.Context, organizationID pgtype.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, rolesByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.ID, &i.OrganizationID, &i.Name, &i.Description, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const deleteRolePermissions = `-- name: DeleteRolePermissions :exec
DELETE FROM role_permissions WHERE role_id = $1
`

func (q *Queries) DeleteRolePermissions(ctx context.Context, roleID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRolePermissions, roleID)
	return err
}

const insertRolePermission = `-- name: InsertRolePermission :exec
INSERT INTO role_permissions (role_id, permission_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertRolePermissionParams struct {
	RoleID       pgtype.UUID
	PermissionID pgtype.UUID
}

func (q *Queries) InsertRolePermission(ctx context.Context, arg InsertRolePermissionParams) error {
	_, err := q.db.Exec(ctx, insertRolePermission, arg.RoleID, arg.PermissionID)
	return err
}

const permissionsByRoleID = `-- name: PermissionsByRoleID :many
SELECT p.name FROM permissions p
  JOIN role_permissions rp ON rp.permission_id = p.id
 WHERE rp.role_id = $1
 ORDER BY p.name ASC
`

func (q *Queries) PermissionsByRoleID(ctx context.Context, roleID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, permissionsByRoleID, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var s string
		if err := rows.Scan(&s); err != nil {
			return nil, err
		}
		items = append(items, s)
	}
	return items, rows.Err()
}

const grantUserRole = `-- name: GrantUserRole :exec
INSERT INTO user_roles (user_id, role_id, granted_at, granted_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, role_id) DO NOTHING
`

type GrantUserRoleParams struct {
	UserID    pgtype.UUID
	RoleID    pgtype.UUID
	GrantedAt pgtype.Timestamptz
	GrantedBy pgtype.UUID
}

func (q *Queries) GrantUserRole(ctx context.Context, arg GrantUserRoleParams) error {
	_, err := q.db.Exec(ctx, grantUserRole, arg.UserID, arg.RoleID, arg.GrantedAt, arg.GrantedBy)
	return err
}

const revokeUserRole = `-- name: RevokeUserRole :execrows
DELETE FROM user_roles WHERE user_id = $1 AND role_id = $2
`

type RevokeUserRoleParams struct {
	UserID pgtype.UUID
	RoleID pgtype.UUID
}

func (q *Queries) RevokeUserRole(ctx context.Context, arg RevokeUserRoleParams) (int64, error) {
	r, err := q.db.Exec(ctx, revokeUserRole, arg.UserID, arg.RoleID)
	if err != nil {
		return 0, err
	}
	return r.RowsAffected(), nil
}

const rolesForUser = `-- name: RolesForUser :many
SELECT r.id, r.organization_id, r.name, r.description, r.created_at, r.updated_at
  FROM roles r
  JOIN user_roles ur ON ur.role_id = r.id
 WHERE ur.user_id = $1
   AND ((r.organization_id IS NULL AND $2::uuid IS NULL) OR r.organization_id = $2::uuid)
 ORDER BY r.name ASC
`

type RolesForUserParams struct {
	UserID         pgtype.UUID
	OrganizationID pgtype.UUID
}

func (q *Queries) RolesForUser(ctx context.Context, arg RolesForUserParams) ([]Role, error) {
	rows, err := q.db.Query(ctx, rolesForUser, arg.UserID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.ID, &i.OrganizationID, &i.Name, &i.Description, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const permissionsForUserInOrg = `-- name: PermissionsForUserInOrg :many
SELECT DISTINCT p.name
  FROM permissions p
  JOIN role_permissions rp ON rp.permission_id = p.id
  JOIN user_roles ur ON ur.role_id = rp.role_id
  JOIN roles r ON r.id = rp.role_id
 WHERE ur.user_id = $1
   AND ((r.organization_id IS NULL AND $2::uuid IS NULL) OR r.organization_id = $2::uuid)
 ORDER BY p.name ASC
`

type PermissionsForUserInOrgParams struct {
	UserID         pgtype.UUID
	OrganizationID pgtype.UUID
}

func (q *Queries) PermissionsForUserInOrg(ctx context.Context, arg PermissionsForUserInOrgParams) ([]string, error) {
	rows, err := q.db.Query(ctx, permissionsForUserInOrg, arg.UserID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var s string
		if err := rows.Scan(&s); err != nil {
			return nil, err
		}
		items = append(items, s)
	}
	return items, rows.Err()
}

const countUsersWithPermissionInOrg = `-- name: CountUsersWithPermissionInOrg :one
SELECT count(DISTINCT ur.user_id) FROM user_roles ur
  JOIN role_permissions rp ON rp.role_id = ur.role_id
  JOIN permissions p ON p.id = rp.permission_id
  JOIN roles r ON r.id = ur.role_id
 WHERE p.name = $1 AND r.organization_id = $2
`

type CountUsersWithPermissionInOrgParams struct {
	Name           string
	OrganizationID pgtype.UUID
}

func (q *Queries) CountUsersWithPermissionInOrg(ctx context.Context, arg CountUsersWithPermissionInOrgParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersWithPermissionInOrg, arg.Name, arg.OrganizationID)
	var n int64
	err := row.Scan(&n)
	return n, err
}

// ---------- audit_events ----------

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit_events (
    id, organization_id, actor_user_id, actor_session_id,
    action, target_type, target_id, metadata, ip, user_agent, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertAuditEventParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	ActorUserID    pgtype.UUID
	ActorSessionID pgtype.UUID
	Action         string
	TargetType     pgtype.Text
	TargetID       pgtype.Text
	Metadata       []byte
	Ip             pgtype.Text // serialised inet via host(), see postgres_v10.go
	UserAgent      pgtype.Text
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.ID, arg.OrganizationID, arg.ActorUserID, arg.ActorSessionID,
		arg.Action, arg.TargetType, arg.TargetID, arg.Metadata, arg.Ip, arg.UserAgent, arg.CreatedAt,
	)
	return err
}
