// Package oauth owns the user-facing OAuth 2.0 login state machine:
// PKCE state generation at /start and code exchange at /callback. Extracted
// from root service_oauth.go in PR H (2026-06-22). The root package exposes
// type aliases for Provider, ProviderToken, and ProviderUser so the public
// API surface is byte-stable.
//
// The handler layer (internal/oauth/handlers) is unchanged and continues to
// consume this package via the Service interface it already defines.
package oauth

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"sync"
	"time"

	"github.com/glincker/theauth-go/crypto"
	"github.com/glincker/theauth-go/internal/audit"
	"github.com/glincker/theauth-go/internal/models"
	"github.com/glincker/theauth-go/internal/ulid"
)

// oauthStateTTL is how long a state token from /start is considered valid
// at /callback. The OAuth round-trip (user agent -> provider -> redirect)
// rarely exceeds a minute or two; 10 minutes is a comfortable upper bound.
const oauthStateTTL = 10 * time.Minute

// oauthStateGCEvery is how often the GC goroutine sweeps the state map for
// expired entries. Keeping it short caps the worst-case footprint under
// burst load.
const oauthStateGCEvery = time.Minute

// oauthState is the per-flow context stored between /start and /callback.
type oauthState struct {
	codeVerifier string
	redirectURI  string
	provider     string
	createdAt    time.Time
}

// Provider is the contract every OAuth 2.0 / OIDC provider implements. Each
// concrete provider lives in its own sub-package under provider/<name>/ so
// consumers can pick what to import (avoids dragging in HTTP clients for
// providers they will never use). Moved here from the root package in PR H
// (2026-06-22); re-exported from root via a type alias so the v0.3+
// stability surface is byte-stable.
type Provider interface {
	// Name returns the stable registry key, e.g. "github". Routes mount as
	// /auth/providers/{name}/start and /auth/providers/{name}/callback, and
	// it lands in oauth_accounts.provider so it must be URL-safe and lower
	// case.
	Name() string

	// AuthURL builds the absolute authorization URL the user agent will be
	// redirected to. state and codeChallenge are generated by the caller;
	// the implementation only assembles the query string.
	AuthURL(state, codeChallenge, redirectURI string, scopes []string) string

	// ExchangeCode trades an authorization code (and PKCE verifier) for a
	// ProviderToken. Implementations should set a request timeout via ctx;
	// the caller will not.
	ExchangeCode(ctx context.Context, code, codeVerifier, redirectURI string) (*ProviderToken, error)

	// UserInfo returns the canonical user profile for the supplied token.
	// Implementations are responsible for picking the best email (verified +
	// primary if the provider distinguishes them) and reflecting that in
	// ProviderUser.EmailVerified.
	UserInfo(ctx context.Context, token *ProviderToken) (*ProviderUser, error)
}

// ProviderToken is the normalized shape of an OAuth token exchange response.
// Providers vary in which fields they populate (e.g. GitHub typically omits
// RefreshToken and ExpiresAt for "no-expiry" tokens). Storage encrypts the
// access/refresh tokens at rest via crypto.Encrypt.
type ProviderToken struct {
	AccessToken  string
	RefreshToken string
	ExpiresAt    time.Time
	Scope        string
	TokenType    string
}

// ProviderUser is the normalized shape of a provider's userinfo response.
// ID is the provider-stable user identifier (e.g. GitHub numeric id as a
// string) and is what oauth_accounts.provider_user_id stores. Email may be
// empty when the user denied the email scope or has no public email on the
// provider; EmailVerified is true only when the provider attests to it.
type ProviderUser struct {
	ID            string
	Email         string
	EmailVerified bool
	Name          string
	AvatarURL     string
}

// Storage is the minimal persistence subset this package needs. Declared
// here (not imported from root) so internal/oauth does not import the
// root theauth package and the constructor cycle stays broken.
type Storage interface {
	UpsertOAuthAccount(ctx context.Context, a models.OAuthAccount) (models.OAuthAccount, error)
	OAuthAccountByProviderUserID(ctx context.Context, provider, providerUserID string) (*models.OAuthAccount, error)
	UserByID(ctx context.Context, id models.ULID) (*models.User, error)
	UserByEmail(ctx context.Context, email string) (*models.User, error)
	CreateUser(ctx context.Context, u models.User) (models.User, error)
}

// SessionIssuer abstracts the session minting call. Allows oauth to issue a
// session at callback time without importing internal/session (the root
// constructor wires the concrete *session.Service in).
type SessionIssuer interface {
	Issue(ctx context.Context, user models.User, userAgent, ip string) (string, models.Session, error)
}

// findBranch records which resolution path findOrCreateUser took so Callback
// can decide whether to fire the OnOAuthConflict hook.
type findBranch int

const (
	foundByProvider findBranch = iota // existing oauth_accounts row for this provider
	foundByEmail                      // user found by email; provider not yet linked
	brandNewUser                      // no prior record; new user was created
)

// ConflictPayload carries provider data when an email-matched user is found.
// Mirrors theauth.OAuthConflictPayload; defined locally to avoid an import
// cycle between internal/oauth and the root package.
type ConflictPayload struct {
	Provider        string
	ProviderUserID  string
	ProviderEmail   string
	ProviderName    string
	ProviderAvatar  string
	ExistingUserID  string
	AccessTokenEnc  []byte
	RefreshTokenEnc []byte
	ExpiresAt       *time.Time
	Scope           string
}

// Service owns the OAuth start/callback state machine.
type Service struct {
	providers       map[string]Provider
	storage         Storage
	baseURL         string
	encKey          []byte
	sessions        SessionIssuer
	auditEm         audit.Emitter
	states          sync.Map // map[string]*oauthState
	stopGC          chan struct{}
	onOAuthConflict func(ctx context.Context, p ConflictPayload) (string, error) // may be nil
}

// New constructs a Service. providers is a name-keyed map; storage satisfies
// the minimal Storage interface; baseURL is the authority origin (e.g.
// "https://example.com") used to build the callback redirect URI; encKey is
// the 32-byte AES key for token encryption; sessions mints sessions at
// callback success; em records audit events. onConflict is the optional hook
// called when a sign-in email matches an existing user registered via a
// different provider; when nil the flow proceeds normally.
func New(providers map[string]Provider, storage Storage, baseURL string, encKey []byte, sessions SessionIssuer, em audit.Emitter, onConflict func(ctx context.Context, p ConflictPayload) (string, error)) *Service {
	if em == nil {
		em = audit.NoopEmitter{}
	}
	s := &Service{
		providers:       providers,
		storage:         storage,
		baseURL:         baseURL,
		encKey:          encKey,
		sessions:        sessions,
		auditEm:         em,
		stopGC:          make(chan struct{}),
		onOAuthConflict: onConflict,
	}
	go s.gcLoop()
	return s
}

// Stop signals the GC goroutine to exit. Safe to call multiple times.
func (s *Service) Stop() {
	select {
	case <-s.stopGC:
	default:
		close(s.stopGC)
	}
}

// HasProvider reports whether the named provider is registered.
func (s *Service) HasProvider(name string) bool {
	_, ok := s.providers[name]
	return ok
}

// Start generates state + PKCE verifier, records them for the upcoming
// callback, and returns the provider's authorization URL plus the raw state
// string (which the handler sets as a short-lived CSRF cookie).
func (s *Service) Start(_ context.Context, providerName string) (authURL, state string, err error) {
	p, ok := s.providers[providerName]
	if !ok {
		return "", "", fmt.Errorf("theauth: unknown provider %q", providerName)
	}
	state, err = crypto.NewToken()
	if err != nil {
		return "", "", err
	}
	verifier, err := crypto.NewCodeVerifier()
	if err != nil {
		return "", "", err
	}
	challenge := crypto.CodeChallenge(verifier)
	redirectURI := s.baseURL + "/auth/providers/" + providerName + "/callback"
	s.states.Store(state, &oauthState{
		codeVerifier: verifier,
		redirectURI:  redirectURI,
		provider:     providerName,
		createdAt:    time.Now(),
	})
	authURL = p.AuthURL(state, challenge, redirectURI, nil)
	return authURL, state, nil
}

// Callback completes the OAuth flow: looks up the state stored at /start,
// exchanges the code, fetches user info, finds-or-creates the local user,
// upserts the OAuthAccount with encrypted tokens, and issues a session.
// Returns the raw session token, the resolved user, and a created flag
// reporting whether the user row was newly created during this call
// (v2.5: lets the root forwarder distinguish OnSignup from OnSignin
// dispatch).
func (s *Service) Callback(ctx context.Context, providerName, code, state, userAgent, ip string) (sessionToken string, user *models.User, created bool, err error) {
	p, ok := s.providers[providerName]
	if !ok {
		return "", nil, false, fmt.Errorf("theauth: unknown provider %q", providerName)
	}
	raw, ok := s.states.LoadAndDelete(state)
	if !ok {
		return "", nil, false, errors.New("theauth: oauth state unknown or expired")
	}
	st, ok := raw.(*oauthState)
	if !ok {
		return "", nil, false, errors.New("theauth: oauth state corrupted")
	}
	if st.provider != providerName {
		return "", nil, false, errors.New("theauth: oauth state provider mismatch")
	}
	if time.Since(st.createdAt) > oauthStateTTL {
		return "", nil, false, errors.New("theauth: oauth state expired")
	}

	tok, err := p.ExchangeCode(ctx, code, st.codeVerifier, st.redirectURI)
	if err != nil {
		return "", nil, false, fmt.Errorf("theauth: ExchangeCode: %w", err)
	}
	pu, err := p.UserInfo(ctx, tok)
	if err != nil {
		return "", nil, false, fmt.Errorf("theauth: UserInfo: %w", err)
	}
	if pu == nil || pu.ID == "" {
		return "", nil, false, errors.New("theauth: provider returned empty user id")
	}

	resolved, branch, err := s.findOrCreateUser(ctx, providerName, pu)
	if err != nil {
		return "", nil, false, err
	}

	accessEnc, err := crypto.Encrypt(s.encKey, []byte(tok.AccessToken))
	if err != nil {
		return "", nil, false, fmt.Errorf("theauth: encrypt access token: %w", err)
	}
	var refreshEnc []byte
	if tok.RefreshToken != "" {
		refreshEnc, err = crypto.Encrypt(s.encKey, []byte(tok.RefreshToken))
		if err != nil {
			return "", nil, false, fmt.Errorf("theauth: encrypt refresh token: %w", err)
		}
	}
	var expiresAt *time.Time
	if !tok.ExpiresAt.IsZero() {
		e := tok.ExpiresAt
		expiresAt = &e
	}

	// When the user was found by email match (not by provider ID), the incoming
	// provider is not yet linked. If a hook is configured, pause the flow so
	// the consumer can verify ownership before linking.
	if branch == foundByEmail && s.onOAuthConflict != nil {
		p := ConflictPayload{
			Provider:        providerName,
			ProviderUserID:  pu.ID,
			ProviderEmail:   pu.Email,
			ProviderName:    pu.Name,
			ProviderAvatar:  pu.AvatarURL,
			ExistingUserID:  resolved.ID.String(),
			AccessTokenEnc:  accessEnc,
			RefreshTokenEnc: refreshEnc,
			ExpiresAt:       expiresAt,
			Scope:           tok.Scope,
		}
		redirectURL, hookErr := s.onOAuthConflict(ctx, p)
		if hookErr != nil {
			return "", nil, false, fmt.Errorf("theauth: onOAuthConflict hook: %w", hookErr)
		}
		return "", nil, false, &models.OAuthConflictRedirectError{URL: redirectURL}
	}

	now := time.Now()
	oauthRowID := ulid.New()
	if _, err := s.storage.UpsertOAuthAccount(ctx, models.OAuthAccount{
		ID:              oauthRowID,
		UserID:          resolved.ID,
		Provider:        providerName,
		ProviderUserID:  pu.ID,
		AccessTokenEnc:  accessEnc,
		RefreshTokenEnc: refreshEnc,
		ExpiresAt:       expiresAt,
		Scope:           tok.Scope,
		CreatedAt:       now,
		UpdatedAt:       now,
	}); err != nil {
		return "", nil, false, fmt.Errorf("theauth: upsert oauth account: %w", err)
	}

	sessToken, _, err := s.sessions.Issue(ctx, *resolved, userAgent, ip)
	if err != nil {
		return "", nil, false, err
	}
	s.auditEm.EmitAudit(ctx, "oauth_account.linked", models.TargetRef{Type: "oauth_account", ID: oauthRowID.String()}, map[string]any{
		"provider": providerName,
	})
	s.auditEm.EmitAudit(ctx, "user.login", models.TargetRef{Type: "user", ID: resolved.ID.String()}, map[string]any{
		"auth_method": "oauth:" + providerName,
	})
	slog.Info("theauth: oauth signin", "provider", providerName, "user_id", resolved.ID.String())
	return sessToken, resolved, branch == brandNewUser, nil
}

// findOrCreateUser implements the three-branch resolution: (1) existing
// oauth_accounts row -> load that user (foundByProvider), (2) email match ->
// reuse that user (foundByEmail), (3) brand new user (brandNewUser).
func (s *Service) findOrCreateUser(ctx context.Context, providerName string, pu *ProviderUser) (*models.User, findBranch, error) {
	acct, err := s.storage.OAuthAccountByProviderUserID(ctx, providerName, pu.ID)
	if err == nil && acct != nil {
		u, err := s.storage.UserByID(ctx, acct.UserID)
		if err != nil {
			return nil, 0, fmt.Errorf("theauth: load linked user: %w", err)
		}
		return u, foundByProvider, nil
	}
	if err != nil && !errors.Is(err, models.ErrStorageNotFound) {
		return nil, 0, fmt.Errorf("theauth: lookup oauth account: %w", err)
	}

	if pu.Email != "" {
		u, err := s.storage.UserByEmail(ctx, pu.Email)
		if err == nil && u != nil {
			return u, foundByEmail, nil
		}
		if err != nil && !errors.Is(err, models.ErrStorageNotFound) {
			return nil, 0, fmt.Errorf("theauth: lookup user by email: %w", err)
		}
	}

	now := time.Now()
	newUser := models.User{
		ID:        ulid.New(),
		Email:     pu.Email,
		Name:      pu.Name,
		AvatarURL: pu.AvatarURL,
		CreatedAt: now,
		UpdatedAt: now,
	}
	if pu.EmailVerified {
		newUser.EmailVerifiedAt = &now
	}
	created, err := s.storage.CreateUser(ctx, newUser)
	if err != nil {
		return nil, 0, fmt.Errorf("theauth: create oauth user: %w", err)
	}
	return &created, brandNewUser, nil
}

// gcLoop sweeps expired entries from s.states.
func (s *Service) gcLoop() {
	t := time.NewTicker(oauthStateGCEvery)
	defer t.Stop()
	for {
		select {
		case <-s.stopGC:
			return
		case now := <-t.C:
			cutoff := now.Add(-oauthStateTTL)
			s.states.Range(func(k, v any) bool {
				if st, ok := v.(*oauthState); ok && st.createdAt.Before(cutoff) {
					s.states.Delete(k)
				}
				return true
			})
		}
	}
}
