// Package oauth owns the user-facing OAuth 2.0 login state machine:
// PKCE state generation at /start and code exchange at /callback. Extracted
// from root service_oauth.go in PR H (2026-06-22). The root package exposes
// type aliases for Provider, ProviderToken, and ProviderUser so the public
// API surface is byte-stable.
//
// The handler layer (internal/oauth/handlers) is unchanged and continues to
// consume this package via the Service interface it already defines.
package oauth

import (
	"context"
	"crypto/sha256"
	"crypto/subtle"
	"errors"
	"fmt"
	"log/slog"
	"strings"
	"time"

	"github.com/glincker/theauth-go/v2/crypto"
	"github.com/glincker/theauth-go/v2/internal/audit"
	"github.com/glincker/theauth-go/v2/internal/models"
	"github.com/glincker/theauth-go/v2/internal/pathprefix"
	"github.com/glincker/theauth-go/v2/internal/ulid"
)

// defaultStateTTL is how long a flow may take between /start and /callback.
const defaultStateTTL = 10 * time.Minute

// Provider is the contract every OAuth 2.0 / OIDC provider implements. Each
// concrete provider lives in its own sub-package under provider/<name>/ so
// consumers can pick what to import (avoids dragging in HTTP clients for
// providers they will never use). Moved here from the root package in PR H
// (2026-06-22); re-exported from root via a type alias so the v0.3+
// stability surface is byte-stable.
type Provider interface {
	// Name returns the stable registry key, e.g. "github". Routes mount as
	// /auth/providers/{name}/start and /auth/providers/{name}/callback, and
	// it lands in oauth_accounts.provider so it must be URL-safe and lower
	// case.
	Name() string

	// AuthURL builds the absolute authorization URL the user agent will be
	// redirected to. state and codeChallenge are generated by the caller;
	// the implementation only assembles the query string.
	AuthURL(state, codeChallenge, redirectURI string, scopes []string) string

	// ExchangeCode trades an authorization code (and PKCE verifier) for a
	// ProviderToken. Implementations should set a request timeout via ctx;
	// the caller will not.
	ExchangeCode(ctx context.Context, code, codeVerifier, redirectURI string) (*ProviderToken, error)

	// UserInfo returns the canonical user profile for the supplied token.
	// Implementations are responsible for picking the best email (verified +
	// primary if the provider distinguishes them) and reflecting that in
	// ProviderUser.EmailVerified.
	UserInfo(ctx context.Context, token *ProviderToken) (*ProviderUser, error)
}

// NonceProvider is implemented by OIDC providers. The service generates a
// nonce per flow, passes it into the authorization URL, and the provider
// must verify it against the ID token during the code exchange.
type NonceProvider interface {
	Provider
	AuthURLWithNonce(state, codeChallenge, nonce, redirectURI string, scopes []string) string
	ExchangeCodeWithNonce(ctx context.Context, code, codeVerifier, redirectURI, nonce string) (*ProviderToken, error)
}

// ProviderToken is the normalized shape of an OAuth token exchange response.
// Providers vary in which fields they populate (e.g. GitHub typically omits
// RefreshToken and ExpiresAt for "no-expiry" tokens). Storage encrypts the
// access/refresh tokens at rest via crypto.Encrypt.
type ProviderToken struct {
	AccessToken  string
	RefreshToken string
	ExpiresAt    time.Time
	Scope        string
	TokenType    string
	// IDToken is the verified OIDC ID token, set only by providers that
	// validate it (see NonceProvider). Empty otherwise.
	IDToken string
}

// ProviderUser is the normalized shape of a provider's userinfo response.
// ID is the provider-stable user identifier (e.g. GitHub numeric id as a
// string) and is what oauth_accounts.provider_user_id stores. Email may be
// empty when the user denied the email scope or has no public email on the
// provider; EmailVerified is true only when the provider attests to it.
type ProviderUser struct {
	ID            string
	Email         string
	EmailVerified bool
	Name          string
	AvatarURL     string
}

// Storage is the minimal persistence subset this package needs. Declared
// here (not imported from root) so internal/oauth does not import the
// root theauth package and the constructor cycle stays broken.
type Storage interface {
	UpsertOAuthAccount(ctx context.Context, a models.OAuthAccount) (models.OAuthAccount, error)
	OAuthAccountByProviderUserID(ctx context.Context, provider, providerUserID string) (*models.OAuthAccount, error)
	UserByID(ctx context.Context, id models.ULID) (*models.User, error)
	UserByEmail(ctx context.Context, email string) (*models.User, error)
	CreateUser(ctx context.Context, u models.User) (models.User, error)
}

// SessionIssuer abstracts the session minting call. Allows oauth to issue a
// session at callback time without importing internal/session (the root
// constructor wires the concrete *session.Service in).
type SessionIssuer interface {
	Issue(ctx context.Context, user models.User, userAgent, ip string) (string, models.Session, error)
}

// findBranch records which resolution path findOrCreateUser took so Callback
// can decide whether to fire the OnOAuthConflict hook.
type findBranch int

const (
	foundByProvider findBranch = iota // existing oauth_accounts row for this provider
	foundByEmail                      // user found by email; provider not yet linked
	brandNewUser                      // no prior record; new user was created
)

// ConflictPayload carries provider data when an email-matched user is found.
// Mirrors theauth.OAuthConflictPayload; defined locally to avoid an import
// cycle between internal/oauth and the root package.
type ConflictPayload struct {
	Provider        string
	ProviderUserID  string
	ProviderEmail   string
	ProviderName    string
	ProviderAvatar  string
	ExistingUserID  string
	AccessTokenEnc  []byte
	RefreshTokenEnc []byte
	ExpiresAt       *time.Time
	Scope           string
}

// SignupPolicy values mirror the root OAuthSignupPolicy strings.
const (
	SignupOpen           = "open"
	SignupClosed         = "closed"
	SignupAllowedDomains = "allowed_domains"
	SignupInvite         = "invite"
)

// Errors returned by Callback. Handlers map every one to a generic failure.
var (
	ErrStateInvalid        = errors.New("theauth: oauth state invalid")
	ErrSignupNotAllowed    = errors.New("theauth: oauth signup not allowed")
	ErrUnverifiedEmailLink = errors.New("theauth: oauth email unverified for existing account")
)

// Config is the optional hardening configuration for a Service.
type Config struct {
	StateStore          StateStore
	StateTTL            time.Duration
	AllowedReturnTo     []string
	Signup              string
	AllowedEmailDomains []string
	InviteCheck         func(ctx context.Context, email string) (bool, error)
	// PathPrefix is the route prefix of the callback URI. Empty means "/auth".
	PathPrefix string
}

// StartResult is what Start hands the HTTP layer.
type StartResult struct {
	AuthURL string
	// State is the opaque value sent to the provider.
	State string
	// Binding is the secret the HTTP layer must set as an HttpOnly cookie
	// and present again at Callback; it ties the flow to this browser.
	Binding string
}

// CallbackResult is what Callback hands the HTTP layer on success.
type CallbackResult struct {
	SessionToken string
	ReturnTo     string
}

// Service owns the OAuth start/callback state machine.
type Service struct {
	lookup          ProviderLookup
	storage         Storage
	baseURL         string
	encKey          []byte
	sessions        SessionIssuer
	auditEm         audit.Emitter
	states          StateStore
	ownedStates     *MemoryStateStore
	stateTTL        time.Duration
	cfg             Config
	onOAuthConflict func(ctx context.Context, p ConflictPayload) (string, error) // may be nil
}

// New constructs a Service. providers is a name-keyed map; storage satisfies
// the minimal Storage interface; baseURL is the authority origin (e.g.
// "https://example.com") used to build the callback redirect URI; encKey is
// the 32-byte AES key for token encryption; sessions mints sessions at
// callback success; em records audit events. onConflict is the optional hook
// called when a sign-in email matches an existing user registered via a
// different provider; when nil the flow proceeds normally. cfg may be the
// zero value.
func New(providers map[string]Provider, storage Storage, baseURL string, encKey []byte, sessions SessionIssuer, em audit.Emitter, onConflict func(ctx context.Context, p ConflictPayload) (string, error), cfg Config) *Service {
	if em == nil {
		em = audit.NoopEmitter{}
	}
	s := &Service{
		lookup:          staticLookup(providers),
		storage:         storage,
		baseURL:         baseURL,
		encKey:          encKey,
		sessions:        sessions,
		auditEm:         em,
		states:          cfg.StateStore,
		stateTTL:        cfg.StateTTL,
		cfg:             cfg,
		onOAuthConflict: onConflict,
	}
	if s.stateTTL <= 0 {
		s.stateTTL = defaultStateTTL
	}
	if s.states == nil {
		s.ownedStates = NewMemoryStateStore()
		s.states = s.ownedStates
	}
	if s.cfg.Signup == "" {
		s.cfg.Signup = SignupOpen
	}
	return s
}

// Stop releases the default in-memory state store's sweeper. Safe to call
// multiple times. A caller-supplied StateStore is not touched.
func (s *Service) Stop() {
	if s.ownedStates != nil {
		s.ownedStates.Close()
	}
}

// SetLookup replaces the provider source. Call before the service handles requests.
func (s *Service) SetLookup(l ProviderLookup) { s.lookup = l }

// HasProvider reports whether the named provider is registered.
func (s *Service) HasProvider(name string) bool {
	ok, _ := s.LookupProvider(context.Background(), name)
	return ok
}

// LookupProvider reports whether the named provider exists, failing closed
// with an error when a resolver cannot answer.
func (s *Service) LookupProvider(ctx context.Context, name string) (bool, error) {
	_, ok, err := s.lookup.Lookup(ctx, name)
	return ok, err
}

func (s *Service) provider(ctx context.Context, name string) (Provider, error) {
	p, ok, err := s.lookup.Lookup(ctx, name)
	if err != nil {
		return nil, err
	}
	if !ok {
		return nil, fmt.Errorf("theauth: unknown provider %q", name)
	}
	return p, nil
}

// Start generates state, a PKCE verifier, a browser-binding secret and (for
// OIDC providers) a nonce, records them, and returns the provider's
// authorization URL. returnTo is honored only when it matches the
// configured allow-list.
func (s *Service) Start(ctx context.Context, providerName, returnTo string) (StartResult, error) {
	p, err := s.provider(ctx, providerName)
	if err != nil {
		return StartResult{}, err
	}
	state, err := crypto.NewToken()
	if err != nil {
		return StartResult{}, err
	}
	binding, err := crypto.NewToken()
	if err != nil {
		return StartResult{}, err
	}
	verifier, err := crypto.NewCodeVerifier()
	if err != nil {
		return StartResult{}, err
	}
	challenge := crypto.CodeChallenge(verifier)
	redirectURI := s.baseURL + pathprefix.Normalize(s.cfg.PathPrefix) + "/providers/" + providerName + "/callback"
	st := State{
		Provider:     providerName,
		CodeVerifier: verifier,
		RedirectURI:  redirectURI,
		ReturnTo:     MatchReturnTo(returnTo, s.cfg.AllowedReturnTo),
		BindingHash:  bindingHash(binding),
		CreatedAt:    time.Now(),
	}
	var authURL string
	if np, ok := p.(NonceProvider); ok {
		if st.Nonce, err = crypto.NewToken(); err != nil {
			return StartResult{}, err
		}
		authURL = np.AuthURLWithNonce(state, challenge, st.Nonce, redirectURI, nil)
	} else {
		authURL = p.AuthURL(state, challenge, redirectURI, nil)
	}
	if err := s.states.Put(ctx, state, st, s.stateTTL); err != nil {
		return StartResult{}, fmt.Errorf("theauth: store oauth state: %w", err)
	}
	return StartResult{AuthURL: authURL, State: state, Binding: binding}, nil
}

func bindingHash(binding string) []byte {
	h := sha256.Sum256([]byte(binding))
	return h[:]
}

// HasUnsafeRedirectChars reports whether s holds a backslash or an ASCII
// control character. Browsers drop tabs and newlines and read a backslash as
// a slash, so "/<TAB>/host" or "/\host" would otherwise turn into "//host".
func HasUnsafeRedirectChars(s string) bool {
	for _, r := range s {
		if r < 0x20 || r == 0x7f || r == '\\' {
			return true
		}
	}
	return false
}

// MatchReturnTo returns candidate when it matches an allow-list entry, else
// "". Entries are exact absolute URLs or "/" paths; a trailing "*" makes an
// entry a prefix match. Protocol-relative and backslash forms never match.
func MatchReturnTo(candidate string, allow []string) string {
	if candidate == "" || len(allow) == 0 || HasUnsafeRedirectChars(candidate) {
		return ""
	}
	if strings.HasPrefix(candidate, "//") || strings.HasPrefix(candidate, "/\\") {
		return ""
	}
	for _, e := range allow {
		if prefix, ok := strings.CutSuffix(e, "*"); ok {
			if strings.HasPrefix(candidate, prefix) && sameKind(candidate, prefix) {
				return candidate
			}
		} else if candidate == e {
			return candidate
		}
	}
	return ""
}

func sameKind(candidate, prefix string) bool {
	return strings.HasPrefix(candidate, "/") == strings.HasPrefix(prefix, "/") && prefix != ""
}

// Callback completes the OAuth flow: consumes the state stored at /start,
// checks it is bound to the browser presenting binding, exchanges the code,
// fetches user info, finds-or-creates the local user under the signup
// policy, upserts the OAuthAccount with encrypted tokens, and issues a
// session. created reports whether the user row was newly created during
// this call (lets the root forwarder distinguish OnSignup from OnSignin).
func (s *Service) Callback(ctx context.Context, providerName, code, state, binding, userAgent, ip string) (res CallbackResult, user *models.User, created bool, err error) {
	p, err := s.provider(ctx, providerName)
	if err != nil {
		return CallbackResult{}, nil, false, err
	}
	st, err := s.states.Take(ctx, state)
	if err != nil {
		s.emitFailure(ctx, providerName, "state_unknown")
		return CallbackResult{}, nil, false, fmt.Errorf("%w: %v", ErrStateInvalid, err)
	}
	if st.Provider != providerName {
		s.emitFailure(ctx, providerName, "state_provider_mismatch")
		return CallbackResult{}, nil, false, fmt.Errorf("%w: provider mismatch", ErrStateInvalid)
	}
	if time.Since(st.CreatedAt) > s.stateTTL {
		s.emitFailure(ctx, providerName, "state_expired")
		return CallbackResult{}, nil, false, fmt.Errorf("%w: expired", ErrStateInvalid)
	}
	if binding == "" || subtle.ConstantTimeCompare(bindingHash(binding), st.BindingHash) != 1 {
		s.emitFailure(ctx, providerName, "state_binding_mismatch")
		return CallbackResult{}, nil, false, fmt.Errorf("%w: browser binding mismatch", ErrStateInvalid)
	}

	var tok *ProviderToken
	if np, ok := p.(NonceProvider); ok {
		tok, err = np.ExchangeCodeWithNonce(ctx, code, st.CodeVerifier, st.RedirectURI, st.Nonce)
	} else {
		tok, err = p.ExchangeCode(ctx, code, st.CodeVerifier, st.RedirectURI)
	}
	if err != nil {
		s.emitFailure(ctx, providerName, "exchange_failed")
		return CallbackResult{}, nil, false, fmt.Errorf("theauth: ExchangeCode: %w", err)
	}
	pu, err := p.UserInfo(ctx, tok)
	if err == nil && pu != nil {
		pu.Email = strings.ToLower(strings.TrimSpace(pu.Email))
	}
	if err != nil {
		return CallbackResult{}, nil, false, fmt.Errorf("theauth: UserInfo: %w", err)
	}
	if pu == nil || pu.ID == "" {
		return CallbackResult{}, nil, false, errors.New("theauth: provider returned empty user id")
	}

	resolved, branch, err := s.findOrCreateUser(ctx, providerName, pu)
	if err != nil {
		if errors.Is(err, ErrSignupNotAllowed) || errors.Is(err, ErrUnverifiedEmailLink) {
			s.emitFailure(ctx, providerName, "signup_refused")
		}
		return CallbackResult{}, nil, false, err
	}

	accessEnc, err := crypto.Encrypt(s.encKey, []byte(tok.AccessToken))
	if err != nil {
		return CallbackResult{}, nil, false, fmt.Errorf("theauth: encrypt access token: %w", err)
	}
	var refreshEnc []byte
	if tok.RefreshToken != "" {
		refreshEnc, err = crypto.Encrypt(s.encKey, []byte(tok.RefreshToken))
		if err != nil {
			return CallbackResult{}, nil, false, fmt.Errorf("theauth: encrypt refresh token: %w", err)
		}
	}
	var expiresAt *time.Time
	if !tok.ExpiresAt.IsZero() {
		e := tok.ExpiresAt
		expiresAt = &e
	}

	// When the user was found by email match (not by provider ID), the incoming
	// provider is not yet linked. If a hook is configured, pause the flow so
	// the consumer can verify ownership before linking.
	if branch == foundByEmail && s.onOAuthConflict != nil {
		p := ConflictPayload{
			Provider:        providerName,
			ProviderUserID:  pu.ID,
			ProviderEmail:   pu.Email,
			ProviderName:    pu.Name,
			ProviderAvatar:  pu.AvatarURL,
			ExistingUserID:  resolved.ID.String(),
			AccessTokenEnc:  accessEnc,
			RefreshTokenEnc: refreshEnc,
			ExpiresAt:       expiresAt,
			Scope:           tok.Scope,
		}
		redirectURL, hookErr := s.onOAuthConflict(ctx, p)
		if hookErr != nil {
			return CallbackResult{}, nil, false, fmt.Errorf("theauth: onOAuthConflict hook: %w", hookErr)
		}
		return CallbackResult{}, nil, false, &models.OAuthConflictRedirectError{URL: redirectURL}
	}

	now := time.Now()
	oauthRowID := ulid.New()
	if _, err := s.storage.UpsertOAuthAccount(ctx, models.OAuthAccount{
		ID:              oauthRowID,
		UserID:          resolved.ID,
		Provider:        providerName,
		ProviderUserID:  pu.ID,
		AccessTokenEnc:  accessEnc,
		RefreshTokenEnc: refreshEnc,
		ExpiresAt:       expiresAt,
		Scope:           tok.Scope,
		CreatedAt:       now,
		UpdatedAt:       now,
	}); err != nil {
		return CallbackResult{}, nil, false, fmt.Errorf("theauth: upsert oauth account: %w", err)
	}

	sessToken, _, err := s.sessions.Issue(ctx, *resolved, userAgent, ip)
	if err != nil {
		return CallbackResult{}, nil, false, err
	}
	s.auditEm.EmitAudit(ctx, "oauth_account.linked", models.TargetRef{Type: "oauth_account", ID: oauthRowID.String()}, map[string]any{
		"provider": providerName,
	})
	s.auditEm.EmitAudit(ctx, "user.login", models.TargetRef{Type: "user", ID: resolved.ID.String()}, map[string]any{
		"auth_method": "oauth:" + providerName,
	})
	slog.Info("theauth: oauth signin", "provider", providerName, "user_id", resolved.ID.String())
	return CallbackResult{SessionToken: sessToken, ReturnTo: st.ReturnTo}, resolved, branch == brandNewUser, nil
}

// findOrCreateUser implements the three-branch resolution: (1) existing
// oauth_accounts row -> load that user (foundByProvider), (2) email match ->
// reuse that user (foundByEmail), (3) brand new user (brandNewUser).
func (s *Service) findOrCreateUser(ctx context.Context, providerName string, pu *ProviderUser) (*models.User, findBranch, error) {
	acct, err := s.storage.OAuthAccountByProviderUserID(ctx, providerName, pu.ID)
	if err == nil && acct != nil {
		u, err := s.storage.UserByID(ctx, acct.UserID)
		if err != nil {
			return nil, 0, fmt.Errorf("theauth: load linked user: %w", err)
		}
		return u, foundByProvider, nil
	}
	if err != nil && !errors.Is(err, models.ErrStorageNotFound) {
		return nil, 0, fmt.Errorf("theauth: lookup oauth account: %w", err)
	}

	if pu.Email != "" {
		u, err := s.storage.UserByEmail(ctx, pu.Email)
		if err == nil && u != nil {
			if !pu.EmailVerified {
				return nil, 0, ErrUnverifiedEmailLink
			}
			return u, foundByEmail, nil
		}
		if err != nil && !errors.Is(err, models.ErrStorageNotFound) {
			return nil, 0, fmt.Errorf("theauth: lookup user by email: %w", err)
		}
	}

	if err := s.checkSignup(ctx, pu); err != nil {
		return nil, 0, err
	}
	now := time.Now()
	newUser := models.User{
		ID:        ulid.New(),
		Email:     pu.Email,
		Name:      pu.Name,
		AvatarURL: pu.AvatarURL,
		CreatedAt: now,
		UpdatedAt: now,
	}
	if pu.EmailVerified {
		newUser.EmailVerifiedAt = &now
	}
	created, err := s.storage.CreateUser(ctx, newUser)
	if err != nil {
		return nil, 0, fmt.Errorf("theauth: create oauth user: %w", err)
	}
	return &created, brandNewUser, nil
}

// checkSignup applies the configured new-user policy to a verified identity.
func (s *Service) checkSignup(ctx context.Context, pu *ProviderUser) error {
	switch s.cfg.Signup {
	case SignupClosed:
		return ErrSignupNotAllowed
	case SignupAllowedDomains:
		at := strings.LastIndex(pu.Email, "@")
		if !pu.EmailVerified || at < 0 {
			return ErrSignupNotAllowed
		}
		domain := pu.Email[at+1:]
		for _, d := range s.cfg.AllowedEmailDomains {
			if strings.EqualFold(strings.TrimSpace(d), domain) {
				return nil
			}
		}
		return ErrSignupNotAllowed
	case SignupInvite:
		if !pu.EmailVerified || s.cfg.InviteCheck == nil {
			return ErrSignupNotAllowed
		}
		ok, err := s.cfg.InviteCheck(ctx, pu.Email)
		if err != nil {
			return fmt.Errorf("theauth: invite check: %w", err)
		}
		if !ok {
			return ErrSignupNotAllowed
		}
	}
	return nil
}

func (s *Service) emitFailure(ctx context.Context, providerName, reason string) {
	s.auditEm.EmitAudit(ctx, "login.failed", models.TargetRef{}, map[string]any{
		"auth_method": "oauth:" + providerName,
		"reason":      reason,
	})
}
