ALTER TABLE users DROP COLUMN IF EXISTS display_name;
ALTER TABLE users DROP COLUMN IF EXISTS family_name;
ALTER TABLE users DROP COLUMN IF EXISTS given_name;
ALTER TABLE users DROP COLUMN IF EXISTS external_id;
DROP TABLE IF EXISTS group_members;
DROP TABLE IF EXISTS groups;
DROP TABLE IF EXISTS scim_tokens;
